import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="w-full h-[48px]">
          <div className="w-full px-8 h-full bg-stone-700 flex">
            <div className="h-full text-white flex items-center justify-center hover:bg-stone-900 hover:cursor-pointer px-4">Bada Bing</div>
            <div className="h-full text-white flex items-center justify-center hover:bg-stone-900 hover:cursor-pointer px-4">Bada Boom</div>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
